---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: kproducer
  namespace: flux-system
spec:
  DependsOn:
  - name: kafka-cluster
  interval: 10m0s
  path: ./releases/kproducer
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client