---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: kafka-cluster
  namespace: flux-system
spec:
  dependsOn:
  - name: kafka-operator
  interval: 10m0s
  path: ./releases/kafka-cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
