---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: kconsumer
  namespace: flux-system
spec:
  dependsOn:
  - name: kproducer
  interval: 10m0s
  path: ./releases/kconsumer
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
